name: Build

on:
  workflow_call:
    inputs:
      publish-artifact:
        default: false
        required: false
        type: boolean
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:      
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            protobuf-compiler

      - name: Rust Setup
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "stable"
          targets: "x86_64-unknown-linux-musl"
      - uses: Swatinem/rust-cache@v2

      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: musl-tools # provides musl-gcc
          version: 1.0

      - name: Build the project to `musl` output
        run: "cargo build --release --target x86_64-unknown-linux-musl"

      - run: touch config.toml

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        if: ${{ inputs.publish-artifact }}
        with:
          name: build-musl
          path: |
            target/x86_64-unknown-linux-musl/release/naitik-yral-multiple-services
            config.toml

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Import Secrets from Vault
        uses: hashicorp/vault-action@v3
        with:
          url: https://vault.yral.com
          method: jwt
          role: naitik-yral-multiple-services-role
          jwtGithubAudience: "https://github.com/dolr-ai"
          secrets: |
            secret/data/naitik-yral-multiple-services/DRAGONFLY_REDIS_STORE_CA_CERT value | DRAGONFLY_REDIS_STORE_CA_CERT ;
            secret/data/naitik-yral-multiple-services/DRAGONFLY_REDIS_STORE_CLIENT_CERT value | DRAGONFLY_REDIS_STORE_CLIENT_CERT ;
            secret/data/naitik-yral-multiple-services/DRAGONFLY_REDIS_STORE_CLIENT_KEY value | DRAGONFLY_REDIS_STORE_CLIENT_KEY ;
            secret/data/naitik-yral-multiple-services/DRAGONFLY_REDIS_STORE_HOSTS value | DRAGONFLY_REDIS_STORE_HOSTS ;
            secret/data/naitik-yral-multiple-services/DRAGONFLY_REDIS_STORE_PASSWORD value | DRAGONFLY_REDIS_STORE_PASSWORD ;

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Rust Setup
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "stable"
          components: "clippy,rustfmt"
      
      - name: Lint check
        run: |
          cargo fmt --check
          cargo clippy --no-deps --all-features --release -- -Dwarnings

      - name: Run tests
        # Need to do sequential tests as upstash has really bad timeouts under load most of the bulk methods wont have more than 5 queries at a time, so it should be fine.
        run: cargo test
        env:
          DRAGONFLY_REDIS_STORE_CA_CERT: ${{ env.DRAGONFLY_REDIS_STORE_CA_CERT }}
          DRAGONFLY_REDIS_STORE_CLIENT_CERT: ${{ env.DRAGONFLY_REDIS_STORE_CLIENT_CERT }}
          DRAGONFLY_REDIS_STORE_CLIENT_KEY: ${{ env.DRAGONFLY_REDIS_STORE_CLIENT_KEY }}
          DRAGONFLY_REDIS_STORE_HOSTS: ${{ env.DRAGONFLY_REDIS_STORE_HOSTS }}
          DRAGONFLY_REDIS_STORE_PASSWORD: ${{ env.DRAGONFLY_REDIS_STORE_PASSWORD }}